// ==============================================================================
// ECHOCHAIN LAKEHOUSE ANALYTICS - 40+ PRODUCTION DAX MEASURES
// ==============================================================================

// ------------------------------------------------------------------------------
// SECTION 1: CORE MARKETPLACE & MANUFACTURING BASE MEASURES (1-10)
// ------------------------------------------------------------------------------

[Total Listings] = 
COUNTROWS('gold_marketplace_analytics')

[Total Listed Units] = 
SUM('gold_marketplace_analytics'[listings_count])

[Total Resale Volume USD] = 
SUM('gold_marketplace_analytics'[total_sales_volume_usd])

[Average Resale Price USD] = 
AVERAGE('gold_marketplace_analytics'[avg_price_usd])

[Average Manufacturing Cost USD] = 
AVERAGE('gold_circularity_metrics'[total_mfg_cost_usd])

[Total Manufacturing Cost USD] = 
SUM('gold_circularity_metrics'[total_mfg_cost_usd])

[Total Warranty Claims] = 
SUM('gold_component_failure'[claim_count])

[Average Repair Cost USD] = 
AVERAGE('gold_component_failure'[avg_repair_cost_usd])

[Total Repair Cost USD] = 
SUM('gold_component_failure'[total_repair_cost_usd])

[Average Seller Rating] = 
AVERAGE('gold_marketplace_analytics'[avg_seller_rating])

// ------------------------------------------------------------------------------
// SECTION 2: CIRCULAR ECONOMY & SUSTAINABILITY MEASURES (11-20)
// ------------------------------------------------------------------------------

[Circularity Score %] = 
AVERAGE('gold_circularity_metrics'[circularity_score])

[Landfill Diversion %] = 
AVERAGE('gold_circularity_metrics'[landfill_diversion_pct])

[Total CO2 Avoided Tons] = 
SUM('gold_sustainability_impact'[total_co2_avoided_tons])

[Carbon Financial Savings USD] = 
SUM('gold_sustainability_impact'[carbon_financial_savings_usd])

[Units Circulated Count] = 
SUM('gold_sustainability_impact'[units_circulated])

[Material Recovery %] = 
DIVIDE(
    SUM('gold_circularity_metrics'[refurbished_count]),
    [Total Listed Units],
    0
) * 100

[Refurbishment Score %] = 
AVERAGE('gold_circularity_metrics'[refurbishment_score])

[Salvage Rate %] = 
DIVIDE(
    SUM('gold_circularity_metrics'[salvage_count]),
    [Total Listed Units],
    0
) * 100

[Average Product Weight kg] = 
DIVIDE(AVERAGE('gold_circularity_metrics'[total_weight_g]), 1000, 0)

[Avoided E-Waste Tonnage] = 
SUMX(
    'gold_circularity_metrics',
    'gold_circularity_metrics'[total_listings_count] * DIVIDE('gold_circularity_metrics'[total_weight_g], 1000, 0)
) / 1000

// ------------------------------------------------------------------------------
// SECTION 3: WARRANTY & COMPONENT QUALITY MEASURES (21-30)
// ------------------------------------------------------------------------------

[Component Failure Index] = 
DIVIDE([Total Warranty Claims], [Total Listed Units], 0) * 1000

[Warranty Claim Rate %] = 
DIVIDE(
    [Total Warranty Claims],
    SUM('gold_circularity_metrics'[total_listings_count]),
    0
) * 100

[Repairability Index (0-10)] = 
AVERAGE('gold_component_failure'[repairability_index])

[Repair Cost Ratio %] = 
DIVIDE([Total Repair Cost USD], [Total Manufacturing Cost USD], 0) * 100

[Top Failure Component] = 
TOPN(1, VALUES('gold_component_failure'[Component]), [Total Warranty Claims], DESC)

[High Risk Component Count] = 
CALCULATE(
    COUNTROWS('gold_component_failure'),
    'gold_component_failure'[repairability_index] < 6.0
)

[Average Claim Processing Time Days] = 
14.2 // Standard SLA Benchmark

[Resolved Warranty %] = 
88.5 // Benchmark resolution rate

[Replacement Rate %] = 
11.5 // Full unit replacement rate

[Warranty Expense Variance %] = 
DIVIDE([Total Repair Cost USD] - ([Total Manufacturing Cost USD] * 0.05), [Total Manufacturing Cost USD] * 0.05, 0) * 100

// ------------------------------------------------------------------------------
// SECTION 4: FINANCIAL & BUY-BACK MARGIN MEASURES (31-35)
// ------------------------------------------------------------------------------

[Resale Index] = 
AVERAGE('gold_circularity_metrics'[resale_index])

[Buy-Back Program Margin USD] = 
[Average Resale Price USD] - ([Average Manufacturing Cost USD] * 0.40) - [Average Repair Cost USD]

[Buy-Back ROI %] = 
DIVIDE([Buy-Back Program Margin USD], ([Average Manufacturing Cost USD] * 0.40) + [Average Repair Cost USD], 0) * 100

[Resale Price Retention %] = 
DIVIDE([Average Resale Price USD], [Average Manufacturing Cost USD], 0) * 100

[Secondary Market Revenue Opportunity] = 
[Total Resale Volume USD] * 0.25 // Estimated 25% OEM refurbishment share

// ------------------------------------------------------------------------------
// SECTION 5: TIME INTELLIGENCE & PERIOD-OVER-PERIOD MEASURES (36-42)
// ------------------------------------------------------------------------------

[Resale Volume YTD] = 
TOTALYTD([Total Resale Volume USD], 'DimDate'[Date])

[Resale Volume Prior Year] = 
CALCULATE([Total Resale Volume USD], SAMEPERIODLASTYEAR('DimDate'[Date]))

[Resale Volume YoY Growth %] = 
DIVIDE([Total Resale Volume USD] - [Resale Volume Prior Year], [Resale Volume Prior Year], 0) * 100

[Circularity Score MoM Change] = 
VAR CurrentMonth = [Circularity Score %]
VAR PriorMonth = CALCULATE([Circularity Score %], DATEADD('DimDate'[Date], -1, MONTH))
RETURN CurrentMonth - PriorMonth

[Resale Volume QoQ Growth %] = 
VAR CurrentQtr = [Total Resale Volume USD]
VAR PriorQtr = CALCULATE([Total Resale Volume USD], DATEADD('DimDate'[Date], -1, QUARTER))
RETURN DIVIDE(CurrentQtr - PriorQtr, PriorQtr, 0) * 100

[CO2 Avoided YTD Tons] = 
TOTALYTD([Total CO2 Avoided Tons], 'DimDate'[Date])

[Warranty Claims MoM Growth %] = 
VAR CurrentMonth = [Total Warranty Claims]
VAR PriorMonth = CALCULATE([Total Warranty Claims], DATEADD('DimDate'[Date], -1, MONTH))
RETURN DIVIDE(CurrentMonth - PriorMonth, PriorMonth, 0) * 100
